const songPool = [
    // Your original indie starters
    { artist: "Men I Trust", track: "Show Me How" },
    { artist: "Beach Fossils", track: "Down the Line" },
    { artist: "Crumb", track: "Locket" },
    { artist: "Alvvays", track: "Archie, Marry Me" },
    { artist: "Faye Webster", track: "Kingston" },
    { artist: "The Drums", track: "Money" },
    { artist: "Mac DeMarco", track: "Chamber Of Reflection" },
    { artist: "Vacations", track: "Young" },
    { artist: "No Vacation", track: "Yam Yam" },
    { artist: "Snail Mail", track: "Pristine" },
    { artist: "Unknown Mortal Orchestra", track: "Hunnybee" },
    { artist: "Mild High Club", track: "Homage" },
    { artist: "DIIV", track: "Under the Sun" },
    { artist: "Wild Nothing", track: "Chinatown" },
    { artist: "Japanese Breakfast", track: "Be Sweet" },
    { artist: "Soccer Mommy", track: "Your Dog" },
    { artist: "Her's", track: "What Once Was" },
    { artist: "Peach Pit", track: "Alrighty Aphrodite" },
    { artist: "Yellow Days", track: "A Little While" },
    { artist: "HOMESHAKE", track: "Every Single Thing" },
    { artist: "Good Morning", track: "Warned You" },
    { artist: "Roar", track: "I Can't Handle Change" },
    { artist: "The Walters", track: "I Love You So" },
    { artist: "Vansire", track: "That I Miss You" },
    { artist: "Current Joys", track: "Kids" },
    { artist: "Inner Wave", track: "American Fascism" },
    { artist: "King Krule", track: "Baby Blue" },
    { artist: "Boy Pablo", track: "Dance, Baby!" },
    { artist: "Loving", track: "Visions" },
    { artist: "STRFKR", track: "Golden Light" },
    { artist: "Goth Babe", track: "Weekend Friend" },
    { artist: "Still Woozy", track: "Goodie Bag" },
    { artist: "Big Thief", track: "Paul" },
    { artist: "Whitney", track: "No Woman" },
    { artist: "Tennis", track: "Need Your Love" },
    { artist: "Khruangbin", track: "Texas Sun" },
    { artist: "TOPS", track: "Way To Be Loved" },
    { artist: "Melody's Echo Chamber", track: "I Follow You" },
    { artist: "Blood Orange", track: "You're Not Good Enough" },
    { artist: "Hippo Campus", track: "Buttercup" },
    { artist: "COIN", track: "Talk Too Much" },
    { artist: "Local Natives", track: "When Am I Gonna Lose You" },
    { artist: "Declan McKenna", track: "Brazil" },
    { artist: "Briston Maroney", track: "Freakin' Out On the Interstate" },
    { artist: "Spacey Jane", track: "Booster Seat" },
    { artist: "The Backseat Lovers", track: "Kilby Girl" },
    { artist: "Toro y Moi", track: "So Many Details" },
    { artist: "Washed Out", track: "Feel It All Around" },
    { artist: "Real Estate", track: "It's Real" },
    { artist: "Slow Pulp", track: "High" },

    // The Massive Expansion Starts Here
    { artist: "Surf Curse", track: "Freaks" },
    { artist: "Dayglow", track: "Can I Call You Tonight?" },
    { artist: "Wallows", track: "Are You Bored Yet?" },
    { artist: "TV Girl", track: "Lovers Rock" },
    { artist: "Clairo", track: "Pretty Girl" },
    { artist: "beabadoobee", track: "Coffee" },
    { artist: "Bane's World", track: "You Say I'm in Love" },
    { artist: "Michael Seyer", track: "Lucky Love" },
    { artist: "Phum Viphurit", track: "Lover Boy" },
    { artist: "Temporex", track: "Care" },
    { artist: "Cuco", track: "Lo Que Siento" },
    { artist: "Summer Salt", track: "Driving to Hawaii" },
    { artist: "Hot Flash Heat Wave", track: "Gutter Girl" },
    { artist: "The Frights", track: "Kids" },
    { artist: "Hockey Dad", track: "Seaweed" },
    { artist: "Skegss", track: "Up In The Clouds" },
    { artist: "Ocean Alley", track: "Confidence" },
    { artist: "Sticky Fingers", track: "How To Fly" },
    { artist: "Lime Cordiale", track: "Robbery" },
    { artist: "Dope Lemon", track: "Marinade" },
    { artist: "Allah-Las", track: "Catamaran" },
    { artist: "The Growlers", track: "Night Ride" },
    { artist: "Mystic Braves", track: "Desert Island" },
    { artist: "La Luz", track: "Call Me in the Day" },
    { artist: "Shannon & The Clams", track: "The Boy" },
    { artist: "The Murlocs", track: "Rolling On" },
    { artist: "The Babe Rainbow", track: "Peace Blossom Boogy" },
    { artist: "Sunbeam Sound Machine", track: "In Your Arms" },
    { artist: "Drugdealer", track: "Suddenly" },
    { artist: "Weyes Blood", track: "Andromeda" },
    { artist: "Foxygen", track: "Shuggie" },
    { artist: "The Lemon Twigs", track: "These Words" },
    { artist: "Woods", track: "Sun City Creeps" },
    { artist: "Kevin Morby", track: "Harlem River" },
    { artist: "Kurt Vile", track: "Pretty Pimpin" },
    { artist: "Courtney Barnett", track: "Avant Gardener" },
    { artist: "Julia Jacklin", track: "Pressure To Party" },
    { artist: "Stella Donnelly", track: "Boys Will Be Boys" },
    { artist: "Angie McMahon", track: "Slow Mover" },
    { artist: "Hatchie", track: "Sure" },
    { artist: "Fazerdaze", track: "Lucky Girl" },
    { artist: "Yumi Zouma", track: "In Camera" },
    { artist: "The Beths", track: "Future Me Hates Me" },
    { artist: "Rolling Blackouts Coastal Fever", track: "French Press" },
    { artist: "Parquet Courts", track: "Wide Awake" },
    { artist: "Bodega", track: "How Did This Happen?!" },
    { artist: "Yard Act", track: "The Overload" },
    { artist: "Dry Cleaning", track: "Scratchcard Lanyard" },
    { artist: "Wet Leg", track: "Chaise Longue" },
    { artist: "Los Bitchos", track: "The Link Is About To Die" },
    { artist: "Altın Gün", track: "Goca Dünya" },
    { artist: "Kikagaku Moyo", track: "Dripping Sun" },
    { artist: "Arc De Soleil", track: "Gothenburg" },
    { artist: "Tommy Guerrero", track: "Water In Your Hands" },
    { artist: "Skinshape", track: "I Didn't Know" },
    { artist: "El Michels Affair", track: "C.R.E.A.M." },
    { episodic: "BADBADNOTGOOD", track: "Time Moves Slow" },
    { artist: "Tom Misch", track: "Disco Yes" },
    { artist: "Jordan Rakei", track: "Mind's Eye" },
    { artist: "Alfa Mist", track: "Keep On" },
    { artist: "Puma Blue", track: "Moon Undah Water" },
    { artist: "Cosmo Pyke", track: "Chronic Sunshine" },
    { artist: "Rex Orange County", track: "Loving Is Easy" },
    { artist: "Syd", track: "Body" },
    { artist: "The Internet", track: "Girl" },
    { artist: "Kali Uchis", track: "Dead To Me" },
    { artist: "Nilüfer Yanya", track: "In Your Head" },
    { artist: "Tirzah", track: "Gladly" },
    { artist: "Kelly Lee Owens", track: "Inner Song" },
    { artist: "Neon Indian", track: "Polish Girl" },
    { artist: "Classixx", track: "Holding On" },
    { artist: "Poolside", track: "Harvest Moon" },
    { artist: "Miami Horror", track: "Sometimes" },
    { artist: "Cut Copy", track: "Lights & Music" },
    { artist: "Bag Raiders", track: "Shooting Stars" },
    { artist: "Com Truise", track: "Brokendate" },
    { artist: "Tycho", track: "Awake" },
    { artist: "Pond", track: "Paint Me Silver" },
    { artist: "GUM", track: "The Blue Marble" },
    { artist: "Thee Oh Sees", track: "The Dream" },
    { artist: "Ty Segall", track: "My Sunshine" },
    { artist: "Fuzz", track: "What's In My Head?" },
    { artist: "Wavves", track: "King of the Beach" },
    { artist: "FIDLAR", track: "No Waves" },
    { artist: "Bass Drum of Death", track: "Crawling After You" },
    { artist: "Ought", track: "Beautiful Blue Sky" },
    { artist: "Protomartyr", track: "Pontiac 87" },
    { artist: "IDLES", track: "Never Fight a Man With a Perm" },
    { artist: "Fontaines D.C.", track: "Boys In The Better Land" },
    { artist: "The Murder Capital", track: "Don't Cling To Life" },
    { artist: "Shame", track: "One Rizla" },
    { artist: "black midi", track: "bmbmbm" },
    { artist: "Black Country, New Road", track: "Athens, France" },
    { artist: "Squid", track: "Houseplants" },
    { artist: "Porridge Radio", track: "Sweet" },
    { artist: "Girl in Red", track: "we fell in love in october" },
    { artist: "Cavetown", track: "Boys Will Be Bugs" },
    { artist: "Chloe Moriondo", track: "I Want To Be With You" },
    { artist: "mxmtoon", track: "prom dress" },
    { artist: "Ricky Montgomery", track: "Line Without a Hook" },
    { artist: "Sir Chloe", track: "Michelle" },
    { artist: "Mother Mother", track: "Hayloft" },
    { artist: "Roar", track: "Christmas Kids" },
    { artist: "Jack Stauber", track: "Buttercup" },
    { artist: "Vundabar", track: "Alien Blues" },
    { artist: "Destroy Boys", track: "I Threw Glass at My Friend's Eyes" },
    { artist: "The Fretellis", track: "Chelsea Dagger" },
    { artist: "Kaiser Chiefs", track: "Ruby" },
    { artist: "The Kooks", track: "Naive" },
    { artist: "Catfish and the Bottlemen", track: "Kathleen" },
    { artist: "The Vaccines", track: "If You Wanna" },
    { artist: "Circa Waves", track: "T-Shirt Weather" },
    { artist: "Blossoms", track: "Charlemagne" },
    { artist: "Sam Fender", track: "Seventeen Going Under" },
    { artist: "Gerry Cinnamon", track: "Belter" },
    { artist: "The Reytons", track: "Slice Of Lime" },
    { artist: "The Snuts", track: "Glasgow" },
    { artist: "Inhaler", track: "My Honest Face" },
    { artist: "Sea Girls", track: "All I Want To Hear You Say" },
    { artist: "The Magic Gang", track: "How Can I Compete" },
    { artist: "Sports Team", track: "Here's The Thing" },
    { artist: "Easy Life", track: "Nightmares" },
    { artist: "Rex Orange County", track: "Sunflower" },
    { artist: "Dominic Fike", track: "3 Nights" },
    { artist: "Omar Apollo", track: "Evergreen" },
    { artist: "Steve Lacy", track: "Dark Red" },
    { artist: "Thundercat", track: "Them Changes" },
    { artist: "Anderson .Paak", track: "Come Down" },
    { artist: "Mac Miller", track: "The Spins" },
    { artist: "Tyler, The Creator", track: "EARFQUAKE" },
    { artist: "Frank Ocean", track: "Pink + White" },
    { artist: "Daniel Caesar", track: "Get You" },
    { artist: "Leon Bridges", track: "River" },
    { artist: "Khruangbin", track: "Time (You and I)" },
    { artist: "Parcels", track: "Tieduprightnow" },
    { artist: "Jungle", track: "Casio" },
    { artist: "Franc Moody", track: "Dopamine" },
    { artist: "L'Impératrice", track: "Agitations tropicales" },
    { artist: "Polo & Pan", track: "Nanã" },
    { artist: "Kavinsky", track: "Nightcall" },
    { artist: "Justice", track: "D.A.N.C.E." },
    { artist: "Daft Punk", track: "Something About Us" },
    { artist: "Gorillaz", track: "Feel Good Inc." },
    { artist: "Blur", track: "Girls & Boys" },
    { artist: "Pulp", track: "Common People" },
    { artist: "Oasis", track: "Don't Look Back In Anger" },
    { artist: "The Stone Roses", track: "Fools Gold" },
    { artist: "Happy Mondays", track: "Step On" },
    { artist: "Primal Scream", track: "Loaded" },
    { artist: "Spiritualized", track: "Ladies and Gentlemen We Are Floating in Space" },
    { artist: "Slowdive", track: "Alison" },
    { artist: "My Bloody Valentine", track: "Only Shallow" },
    { artist: "Cocteau Twins", track: "Cherry-coloured Funk" },
    { artist: "The Cure", track: "Just Like Heaven" },
    { artist: "The Smiths", track: "There Is A Light That Never Goes Out" },
    { artist: "Joy Division", track: "Love Will Tear Us Apart" },
    { artist: "New Order", track: "Bizarre Love Triangle" },
    { artist: "Depeche Mode", track: "Enjoy The Silence" },
    { artist: "Tears For Fears", track: "Everybody Wants To Rule The World" },
    { artist: "Talking Heads", track: "This Must Be The Place" },
    { artist: "Pixies", track: "Where Is My Mind?" },
    { artist: "Sonic Youth", track: "Teen Age Riot" },
    { artist: "Pavement", track: "Cut Your Hair" },
    { artist: "Modest Mouse", track: "Float On" },
    { artist: "Built To Spill", track: "Carry The Zero" },
    { artist: "Dinosaur Jr.", track: "Feel The Pain" },
    { artist: "Guided By Voices", track: "Glad Girls" },
    { artist: "Yo La Tengo", track: "Autumn Sweater" },
    { artist: "Neutral Milk Hotel", track: "In the Aeroplane Over the Sea" },
    { artist: "The Magnetic Fields", track: "The Book of Love" },
    { artist: "Sufjan Stevens", track: "Chicago" },
    { artist: "Elliott Smith", track: "Between The Bars" },
    { artist: "Bright Eyes", track: "First Day Of My Life" },
    { artist: "Death Cab For Cutie", track: "Soul Meets Body" },
    { artist: "The Postal Service", track: "Such Great Heights" },
    { artist: "Iron & Wine", track: "Naked As We Came" },
    { artist: "Fleet Foxes", track: "White Winter Hymnal" },
    { artist: "Bon Iver", track: "Skinny Love" },
    { artist: "The Tallest Man On Earth", track: "The Dreamer" },
    { artist: "Jose Gonzalez", track: "Heartbeats" },
    { artist: "Ben Howard", track: "Only Love" },
    { artist: "Father John Misty", track: "Chateau Lobby #4" },
    { artist: "Lord Huron", track: "The Night We Met" },
    { artist: "Gregory Alan Isakov", track: "Big Black Car" },
    { artist: "Caamp", track: "Vagabond" },
    { artist: "Mt. Joy", track: "Silver Lining" },
    { artist: "Rainbow Kitten Surprise", track: "It's Called: Freefall" },
    { artist: "Houndmouth", track: "Sedona" },
    { artist: "The Head and the Heart", track: "Rivers and Roads" },
    { artist: "Vance Joy", track: "Riptide" },
    { artist: "Milky Chance", track: "Stolen Dance" },
    { artist: "Cage The Elephant", track: "Cigarette Daydreams" },
    { artist: "Young the Giant", track: "Cough Syrup" },
    { artist: "Grouplove", track: "Tongue Tied" },
    { artist: "Foster The People", track: "Pumped Up Kicks" },
    { artist: "MGMT", track: "Kids" },
    { artist: "Empire of the Sun", track: "Walking On A Dream" },
    { artist: "Passion Pit", track: "Take A Walk" },
    { artist: "Phoenix", track: "1901" },
    { artist: "Two Door Cinema Club", track: "What You Know" },
    { artist: "The Wombats", track: "Let's Dance to Joy Division" },
    { artist: "Arctic Monkeys", track: "Do I Wanna Know?" },
    { artist: "The Strokes", track: "Reptilia" },
    { artist: "Interpol", track: "Obstacle 1" },
    { artist: "Yeah Yeah Yeahs", track: "Maps" },
    { artist: "LCD Soundsystem", track: "Dance Yrself Clean" }
];