const songDatabase = {
    "Mac DeMarco": ["Chamber Of Reflection", "My Kind of Woman", "Heart To Heart", "For the First Time", "Freaking Out the Neighborhood", "Moonlight on the River", "No Other Heart", "Still Beating", "Watching Him Fade Away", "Salad Days", "Another One", "20191009 I Like Her", "One More Love Song", "On the Level", "Ode to Viceroy", "Preoccupied", "Blue Boy", "This Old Dog", "Let Her Go", "Passing Out Pieces", "Treat Her Better", "A Heart Like Hers", "My Old Man", "Dreaming", "Cooking Up Something Good", "One Another", "The Way You'd Love Her", "Nobody", "Brother", "The Stars Keep On Calling My Name", "Finally Alone", "Let My Baby Stay", "Without Me", "Goodbye Weekend", "On The Square", "Baby You're Out", "Dreams from Yesterday", "A Wolf Who Wears Sheeps Clothes", "Go Easy", "Pepperoni Playboy", "Still Together", "She's Really All I Need", "All Of Our Yesterdays", "Robson Girl", "Annie", "Jonny's Odyssey", "Only You", "Sister", "Baby's Wearing Blue Jeans", "I've Been Waiting for Her", "Honey Moon", "Just to Put Me Down", "Sherrill", "Boe Zaah", "Don Juan", "Gualala", "Simply Paradise", "Little Dogs March", "My House by the Water", "Hey Cowgirl", "Rock and Roll Night Club", "Here Comes The Cowboy", "Skyless Moon", "Phantom", "Choo Choo", "Avocado Andrew", "Baby Bye Bye", "European Vegas", "Rockaway", "Sweeter", "Portland", "Horse Hot Wee Wee Water", "One More Tear To Cry", "Crescent City", "Me and Jon Hanging On", "Me and Mine", "Moving Like Mike", "Lonely Shredder"],
    
    "Arctic Monkeys": ["Do I Wanna Know?", "505", "Fluorescent Adolescent", "R U Mine?", "Mardy Bum", "I Wanna Be Yours", "Why'd You Only Call Me When You're High?", "Arabella", "Brianstorm", "Crying Lightning", "Snap Out of It", "Cornerstone", "Teddy Picker", "A Certain Romance", "When the Sun Goes Down", "I Bet You Look Good On the Dancefloor", "Four Out of Five", "My Propeller", "One For the Road", "Star Treatment", "Knee Socks", "Do Me a Favour", "Suck It and See", "Old Yellow Bricks", "Riot Van", "The View from the Afternoon", "Fake Tales from San Francisco", "Dancing Shoes", "From the Ritz to the Rubble", "D is for Dangerous", "Balaclava", "This House is a Circus", "The Bad Thing", "Only Ones Who Know", "Pretty Visitors", "Dance Little Liar", "Dangerous Animals", "Secret Door", "Fire and the Thud", "Black Treacle", "The Hellcat Spangled Shalalala", "Don't Sit Down 'Cause I've Moved Your Chair", "Reckless Serenade", "Piledriver Waltz", "Love is a Laserquest", "Fireside", "Stop the World I Wanna Get Off with You", "Body Paint", "There'd Better Be a Mirrorball", "I Ain't Quite Where I Think I Am", "Big Ideas", "Sculptures of Anything Goes", "Tranquility Base Hotel & Casino", "One Point Perspective", "American Sports", "The Ultracheese", "Joining the Dots", "The Afternoon's Hat", "Evil Twin", "Electricity", "2013", "You're So Dark"],

    "Tame Impala": ["The Less I Know The Better", "Borderline", "Let It Happen", "New Person, Same Old Mistakes", "Feels Like We Only Go Backwards", "Eventually", "Elephant", "Yes I'm Changing", "Nangs", "One More Hour", "Is It True", "Lost In Yesterday", "The Moment", "Disciples", "Breathe Deeper", "Cause I'm A Man", "Love/Paranoia", "Patience", "Mind Mischief", "Posthumous Forgiveness", "Past Life", "Reality In Motion", "It Might Be Time", "Solitude Is Bliss", "Apocalypse Dreams", "Why Won't They Talk To Me?", "Gossip", "The Boat I Row", "One More Year", "Alter Ego", "End Of Summer", "It Is Not Meant To Be", "Why Won't You Make Up Your Mind?", "Half Full Glass Of Wine", "Endors Toi", "Instant Destiny", "Sundown Syndrome", "Beverly Laurel", "List Of People (To Try And Forget About)", "On Track", "Keep On Lying", "Lucidity", "Glimmer", "Desire Be Desire Go", "Tomorrow's Dust", "Music To Walk Home By", "Be Above It", "No Choice", "Expectation", "Nothing That Has Happened So Far Has Been Anything We Could Control", "Powerlines", "Taxi's Here", "Jeremy's Storm", "I Don't Really Mind", "She Just Won't Believe Me", "Runway Houses City Clouds", "Sun's Coming Up", "Oblivion", "Wings Of Time", "Wander", "The Bold Arrow Of Time", "Slide Through My Fingers", "Skeleton Tiger", "41 Mosquitoes Flying In Formation"],

    "The 1975": ["About You", "Somebody Else", "Robbers", "It's Not Living (If It's Not With You)", "Love It If We Made It", "The Sound", "Chocolate", "Happiness", "Oh Caroline", "I'm In Love With You", "Be My Mistake", "Sincerity Is Scary", "Sex", "Girls", "A Change of Heart", "TOOTIMETOOTIMETOOTIME", "If You're Too Shy (Let Me Know)", "Paris", "Love Me", "Give Yourself a Try", "The Birthday Party", "Fallingforyou", "Me & You Together Song", "People", "The 1975", "Heart Out", "Settle Down", "Menswear", "She Way Out", "Pressure", "The City", "M.O.N.E.Y.", "Talk!", "An Encounter", "Happiness", "Looking For Somebody (To Love)", "Part Of The Band", "When We Are Together", "I Always Wanna Die (Sometimes)", "I Like America & America Likes Me", "How To Draw / Petrichor", "I've Been In Love With You", "Human Too", "Wintering", "Roadkill", "Bagsy Not In Net", "The End (Music For Cars)", "Inside Your Mind", "Mine", "I couldn't be more in love", "She's American", "Loving Someone", "Lostmyhead", "Nana", "Milk", "Medicine", "The Sound", "UGH!", "Notes On A Conditional Form", "Tonight (I Wish I Was Your Boy)"],

    "TV Girl": ["Lovers Rock", "Not Allowed", "Cigarettes out the Window", "Birds Dont Sing", "Blue Hair", "The Blonde", "Taking What's Not Yours", "Louise", "Hate Yourself", "Daughter of a Cop", "Better in the Dark", "Safeword", "Lise", "For You", "Heaven is a Bedroom", "Anjela", "King of Echo Park", "Song About Me", "The Night in Question", "Jump the Turnstile", "7 Days Till Sunday", "She Smokes in Bed", "I Wonder Who She's Kissing Now", "Pantyhose", "The Getaway", "Valerie", "Grapes Upon the Vine", "The Night Time", "It Evaporates", "Mary Confused", "Talk to Strangers", "Desolation Row", "My Next 40 Years"],

    "Clairo": ["Pretty Girl", "Bags", "Sofia", "Flaming Hot Cheetos", "Amoeba", "Bubble Gum", "4EVER", "Softly", "Zinnias", "Blouse", "White Flag", "Closer to You", "Alewife", "Impossible", "North", "Management", "Harbor", "Just for Today", "Reaper", "Bambi", "Partridge", "I Wouldn't Ask You", "Hello?", "Lakeside", "Better", "Drown", "Get Dirtee", "How", "Nomad", "Sexy to Someone", "Juna", "Terrapin", "Add Up My Love", "Echo", "Slow Dance"],

    "Mac Miller": ["The Spins", "Self Care", "Good News", "Weekend", "Dang!", "Blue World", "Circles", "Ladders", "Hurt Feels", "What's the Use?", "Donald Trump", "2009", "Small Worlds", "My Favorite Part", "Cinderella", "Stay", "Congratulations", "Best Day Ever", "Knock Knock", "Party on Fifth Ave", "Frick Park Market", "Objects in the Mirror", "REMember", "Red Dot Music", "Watching Movies", "Star Room", "Avian", "Gezlo", "The Question", "Fight the Feeling", "Nikes on My Feet", "Kool Aid & Frozen Pizza", "Senior Skip Day", "Surf", "Hand Me Downs", "Woods", "Complicated", "Blue World", "Everybody", "Right", "Floating", "I Can See"],

    "The Neighborhood": ["Sweater Weather", "Daddy Issues", "Softcore", "Reflections", "Stargazing", "Wires", "R.I.P. 2 My Youth", "The Beach", "Afraid", "Female Robbery", "Prey", "Cry Baby", "Compass", "Scary Love", "Void", "You Get Me So High", "Lost in Translation", "Tobacco Sunburst", "Nervous", "Cherry Flavoured", "Pretty Boy", "Devil's Advocate", "Middle of Somewhere", "Warm", "A Little Death", "How", "Single", "Greeting from Califournia"],

    "Beach House": ["Space Song", "Myth", "Lazuli", "PPP", "Silver Soul", "Lemon Glow", "Once Twice Melody", "Levitation", "Wishes", "Take Care", "Wildflower", "Master of None", "Gila", "Norway", "Zebra", "Walk in the Park", "10 Mile Stereo", "Real Love", "Beyond Love", "Bluebird", "Days of Candy", "Rough Song", "Somewhere Tonight", "Black Car", "Dark Spring", "Pay No Mind", "Pink Funeral", "Superstar", "Hurts to Love", "New Romance"],

    "Mitski": ["Your Best American Girl", "Nobody", "Washing Machine Heart", "Francis Forever", "The Only Heartbreaker", "My Love Mine All Mine", "First Love / Late Spring", "Liquid Smooth", "I Bet on Losing Dogs", "Me and My Husband", "Should've Been Me", "Stay Soft", "Love Me More", "Working for the Knife", "Heat Lightning", "The Bug Hunter", "Geyser", "A Pearl", "Two Slow Dancers", "Old Friend", "Townie", "I Don't Smoke", "Happy", "Dan the Dancer", "Once More to See You"],

    "Radiohead": ["Creep", "No Surprises", "Karma Police", "Paranoid Android", "High and Dry", "Fake Plastic Trees", "Everything in Its Right Place", "Idioteque", "Nude", "Weird Fishes/Arpeggi", "Jigsaw Falling Into Place", "Lotus Flower", "Burn the Witch", "Daydreaming", "Present Tense", "True Love Waits", "15 Step", "Bodysnatchers", "All I Need", "Reckoner", "House of Cards", "Just", "My Iron Lung", "Street Spirit (Fade Out)", "Lucky", "The Tourist", "Pyramid Song", "Morning Bell", "Knives Out", "There There", "2+2=5", "Identikit", "Ful Stop"],

    "The Strokes": ["Reptilia", "Last Nite", "The Adults Are Talking", "Someday", "You Only Live Once", "Under Cover of Darkness", "Hard to Explain", "Heart in a Cage", "Threat of Joy", "Ode to the Mets", "Selfless", "Brooklyn Bridge to Chorus", "Bad Decisions", "At The Door", "Eternal Summer", "Is This It", "Barely Legal", "Soma", "Trying Your Luck", "Take It or Leave It", "Automatic Stop", "12:51", "The End Has No End", "I Can't Win", "Machu Picchu", "Taken for a Fool", "Gracia", "All the Time", "One Way Trigger"],

    "MGMT": ["Kids", "Electric Feel", "Time to Pretend", "Little Dark Age", "When You Die", "Me and Michael", "Flash Delirium", "Congratulations", "She Works Out Too Much", "TSLAMP", "Hand It Over", "One Thing Left to Try", "In the Afternoon", "Bubblegum Dog", "Mother Nature", "Dancing in Babylon", "It's Working", "Weekend Wars", "The Youth", "Of Moons, Birds & Monsters"],

    "Glass Animals": ["Gooey", "Heat Waves", "The Other Side of Paradise", "Youth", "Life Itself", "Pork Soda", "Black Mambo", "Tangerine", "Dreamland", "Space Ghost Coast to Coast", "Tokyo Drifting", "Your Love (Déjà Vu)", "I Don't Wanna Talk (I Just Wanna Dance)", "Creatures in Heaven", "A Tear in Space (Airlock)", "Pools", "Hazey", "Cocoa Hooves", "Exxus", "Season 2 Episode 3", "Poplar St", "Cane Shuga"],

    "Phoenix": ["1901", "Lisztomania", "Lasso", "Entertainment", "If I Ever Feel Better", "J-Boy", "Tonight", "Rome", "Ti Amo", "Armistice", "Fences", "Girlfriend", "Trying to Be Cool", "S.O.S. in Bel Air", "Chloroform", "Winter Solstice", "Alpha Zulu", "After Midnight", "Identical"],

    "The Neighborhood": ["Sweater Weather", "Daddy Issues", "Softcore", "Reflections", "Stargazing", "Wires", "R.I.P. 2 My Youth", "The Beach", "Afraid", "Female Robbery", "Prey", "Cry Baby", "Compass", "Scary Love", "Void", "You Get Me So High", "Lost in Translation", "Tobacco Sunburst", "Nervous", "Cherry Flavoured", "Pretty Boy", "Devil's Advocate", "Middle of Somewhere", "Warm", "A Little Death", "How", "Single", "Greeting from Califournia"],

    "Boy Pablo": ["Dance, Baby!", "Everytime", "Feeling Lonely", "Sick Feeling", "Hey Girl", "t-shirt", "Honey", "Rest Up", "Leave Me Alone!", "Ready / Problems", "Beach House", "Losing You", "wuchu know", "i <3 u", "Honey", "JD's Song", "Be Mine", "Limitado", "Mustache", "I'm Really Tired This Days"],

    "Wallows": ["Are You Bored Yet?", "Scrawny", "Remember When", "Pictures of Girls", "Pleaser", "These Days", "OK", "I Don't Want to Talk", "Marvelous", "Treacherous Doctor", "Quarterback", "1980s Horror Film II", "Ground", "Wish Me Luck", "Dig What You Dug", "Sun Tan", "Pulling Leaves Off Trees", "Calling After Me", "Your Apartment", "Bad Dream", "A Warning", "Only Ecstasy", "Anytime, Always"],

    "Foster The People": ["Pumped Up Kicks", "Helena Beat", "Houdini", "Sit Next to Me", "Don't Stop (Color on the Walls)", "Coming of Age", "Call It What You Want", "Lamb's Wool", "Imagination", "Worst Nites", "Style", "Pick U Up", "Lost in Space", "See You in the Afterlife", "The Truth", "Are You What You Want to Be?", "Pseudologia Fantastica", "Best Friend", "Pay the Man", "Loyal Like Sid & Nancy"],

    "The Killers": ["Mr. Brightside", "Somebody Told Me", "When You Were Young", "Human", "Read My Mind", "All These Things That I've Done", "The Man", "Caution", "Smile Like You Mean It", "Spaceman", "Runaways", "Miss Atomic Bomb", "Shot At The Night", "Just Another Girl", "My Own Soul's Warning", "Dying Breed", "Boy", "Your Side of Town", "Bright Lights", "Jenny Was a Friend of Mine", "Bones", "For Reasons Unknown"],

    "Lana Del Rey": ["Summertime Sadness", "Video Games", "Born to Die", "Blue Jeans", "Young and Beautiful", "Ride", "West Coast", "High by the Beach", "Love", "Lust for Life", "Mariners Apartment Complex", "Venice Bitch", "Norman Fucking Rockwell", "The Greatest", "White Dress", "Chemtrails Over the Country Club", "Arcadia", "Did you know that there's a tunnel under Ocean Blvd", "A&W", "Say Yes to Heaven", "Margaret", "Candy Necklace", "Paris, Texas", "Radio", "National Anthem", "Diet Mountain Dew", "Dark Paradise", "Gods & Monsters", "Cola", "Brooklyn Baby", "Shades of Cool", "Ultraviolence", "Terrance Loves You", "Honeymoon", "Cherry", "White Mustang", "Doin' Time", "Cinnamon Girl", "Happiness is a Butterfly", "Tulsa Jesus Freak", "Dark But Just A Game"],

    "The 1975": ["About You", "Somebody Else", "Robbers", "It's Not Living (If It's Not With You)", "Love It If We Made It", "The Sound", "Chocolate", "Happiness", "Oh Caroline", "I'm In Love With You", "Be My Mistake", "Sincerity Is Scary", "Sex", "Girls", "A Change of Heart", "TOOTIMETOOTIMETOOTIME", "If You're Too Shy (Let Me Know)", "Paris", "Love Me", "Give Yourself a Try", "The Birthday Party", "Fallingforyou", "Me & You Together Song", "People", "The 1975", "Heart Out", "Settle Down", "Menswear", "She Way Out", "Pressure", "The City", "M.O.N.E.Y.", "Talk!", "An Encounter", "Happiness", "Looking For Somebody (To Love)", "Part Of The Band", "When We Are Together", "I Always Wanna Die (Sometimes)", "I Like America & America Likes Me", "How To Draw / Petrichor", "I've Been In Love With You", "Human Too", "Wintering", "Roadkill", "Bagsy Not In Net", "The End (Music For Cars)", "Inside Your Mind", "Mine", "I couldn't be more in love", "She's American", "Loving Someone", "Lostmyhead", "Nana", "Milk", "Medicine", "The Sound", "UGH!", "Notes On A Conditional Form", "Tonight (I Wish I Was Your Boy)"],
    
    "Bon Iver": ["Skinny Love", "Holocene", "22 (OVER S∞∞N)", "33 “GOD”", "Hey, Ma", "Faith", "re: Stacks", "For Emma", "The Wolves (Act I and II)", "Lump Sum", "Blindsided", "Creature Fear", "Blood Bank", "Beach Baby", "Babys", "Perth", "Minnesota, WI", "Towers", "Beth/Rest", "715 - CRΣΣKS", "666 ʇ", "8 (circle)", "iMi", "Naeem", "Marion", "Sh'Diah"],
    
    "Vampire Weekend": ["A-Punk", "Harmony Hall", "Campus", "Oxford Comma", "Step", "Walcott", "This Life", "Unbelievers", "Diane Young", "Holiday", "Mansard Roof", "Cape Cod Kwassa Kwassa", "The Kids Don't Stand a Chance", "Horchata", "White Sky", "Cousins", "Giving Up the Gun", "Diplomat's Son", "Ya Hey", "Hannah Hunt", "Bambina", "Capricorn", "Gen-X Cops", "Mary Boone", "Classical"],
    
    "The Smiths": ["There Is A Light That Never Goes Out", "This Charming Man", "How Soon Is Now?", "Heaven Knows I'm Miserable Now", "Bigmouth Strikes Again", "Panic", "The Boy with the Thorn in His Side", "Hand in Glove", "What Difference Does It Make?", "Please, Please, Please, Let Me Get What I Want", "William, It Was Really Nothing", "Stop Me If You Think You've Heard This One Before", "Girlfriend in a Coma", "Shoplifters of the World Unite", "Ask", "Sheila Take a Bow", "Half a Person", "Rubber Ring", "Reel Around the Fountain", "Still Ill", "I Know It's Over", "Some Girls Are Bigger Than Others", "Barbarism Begins at Home"],
    
    "Gorillaz": ["Feel Good Inc.", "Dare", "On Melancholy Hill", "Clint Eastwood", "Rhinestone Eyes", "Humility", "Cracker Island", "Aries", "Tomorrow Comes Today", "19-2000", "Rock the House", "Dirty Harry", "Kids with Guns", "El Mañana", "Stylo", "Empire Ants", "Saturnz Barz", "Andromeda", "The Valley of the Pagans", "Skinny Ape", "Silent Running", "New Gold", "Tormenta"],
    
    "Beach Fossils": ["Down the Line", "Sleep Apnea", "Sugar", "May 1st", "Out in the Way", "Adversity", "Generational Synthetic", "Daydream", "Careless", "Don't Fade Away", "Youth", "Shallow", "Twelve Miles High", "Birthday", "Saint Ivy", "Social Jetlag", "Tangerine", "Be Nothing", "Don't Fade Away", "Seconds", "Run to the Moon", "Anything is Possible"],
    
    "Vacations": ["Young", "Telephones", "Relax", "Honey", "Moving Out", "Home", "Dave Calls", "Next Exit", "Actors", "Avalon", "Terms & Conditions", "Close Quarters", "On Your Own", "No Fun", "Nineties", "Something Here", "Panache", "Glow"],
    
    "Still Woozy": ["Goodie Bag", "Habit", "Window", "Cooks", "Lava", "Wolfcat", "Rocky", "That's Life", "Kennel", "Lucy", "Cheesin'", "BS", "Get By", "Anyhow", "Drake", "Woof", "Run It Back", "Shotput", "Forward", "Lemon"],
    
    "Sufjan Stevens": ["Chicago", "Casimir Pulaski Day", "Mystery of Love", "Fourth of July", "Should Have Known Better", "Video Game", "Death with Dignity", "To Be Alone With You", "For the Widows in Paradise", "The Only Thing", "Futile Devices", "Visions of Gideon", "John My Beloved", "Should Have Known Better", "Will Anybody Ever Love Me?", "A Running Start", "Genuflecting Ghost", "Javelin (To a Buck)"]
};

// The code automatically handles the rest!
const flatSongPool = [];
for (const artist in songDatabase) {
    songDatabase[artist].forEach(track => {
        flatSongPool.push({ artist: artist, track: track });
    });
}